" Colorscheme generated by https://github.com/arcticlimer/djanho
highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = a:bg == '' ? '' : 'guibg=' . a:bg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg  . ' ' . gui
endfunction

let s:Color0 = '#617172'
let s:Color8 = '#96c24e'
let s:Color12 = '#2a2a2a'
let s:Color2 = '#ee3f4d'
let s:Color11 = '#474b4c'
let s:Color4 = '#57c3c2'
let s:Color9 = '#134857'
let s:Color1 = '#e4dfd7'
let s:Color7 = '#f9d367'
let s:Color6 = '#fb9968'
let s:Color5 = '#8abcd1'
let s:Color10 = '#2b312c'
let s:Color3 = '#d276a3'

call s:highlight('Comment', '', s:Color0, '')
call s:highlight('Identifier', '', s:Color1, '')
call s:highlight('Error', '', s:Color2, '')
call s:highlight('Keyword', '', s:Color3, '')
call s:highlight('Conditional', '', s:Color4, '')
call s:highlight('Repeat', '', s:Color4, '')
call s:highlight('Function', '', s:Color5, '')
call s:highlight('Number', '', s:Color6, '')
call s:highlight('TSCharacter', '', s:Color6, '')
call s:highlight('String', '', s:Color7, '')
call s:highlight('Type', '', s:Color8, '')
call s:highlight('StatusLine', '', s:Color9, '')
call s:highlight('WildMenu', s:Color10, s:Color1, '')
call s:highlight('Pmenu', s:Color10, s:Color1, '')
call s:highlight('PmenuSel', s:Color1, '', '')
call s:highlight('PmenuThumb', s:Color10, s:Color1, '')
call s:highlight('Normal', s:Color10, s:Color1, '')
call s:highlight('Visual', s:Color11, '', '')
call s:highlight('CursorLine', s:Color11, '', '')
call s:highlight('ColorColumn', s:Color11, '', '')
call s:highlight('SignColumn', s:Color10, '', '')
call s:highlight('TabLine', s:Color12, '', '')
call s:highlight('TabLineFill', s:Color12, '', '')
call s:highlight('TSPunctDelimiter', '', s:Color1, '')

highlight! link Whitespace Comment
highlight! link Macro Function
highlight! link TSParameterReference TSParameter
highlight! link Operator Keyword
highlight! link TSField Constant
highlight! link Folded Comment
highlight! link TSFuncMacro Macro
highlight! link TSComment Comment
highlight! link TSConditional Conditional
highlight! link CursorLineNr Identifier
highlight! link TSConstant Constant
highlight! link TSConstBuiltin TSVariableBuiltin
highlight! link TSPunctBracket MyTag
highlight! link TSTag MyTag
highlight! link TSNumber Number
highlight! link TSKeyword Keyword
highlight! link TSProperty TSField
highlight! link Repeat Conditional
highlight! link NonText Comment
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link TSLabel Type
highlight! link TSOperator Operator
highlight! link TSTagDelimiter Type
highlight! link TSRepeat Repeat
highlight! link TSString String
highlight! link Conditional Operator
highlight! link TSNamespace TSType
highlight! link TSFloat Number
highlight! link TelescopeNormal Normal
highlight! link TSParameter Constant
highlight! link TSFunction Function
highlight! link TSType Type
